name: smart_vendor_app
description: "Smart Street-Vendor Location Optimizer - Lagos Case Study"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.2.2
  shared_preferences: ^2.2.3
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
